-- UPDATE THE QUERY
UPDATE PEOPLE
SET TEAM = 'Sweeties'
WHERE SPID IN ('SP08','SP17','SP21','SP22','SP28');

SELECT *
FROM PEOPLE;

-- GROUP BY
-- 1.
SELECT GEOID, SUM(AMOUNT), AVG(AMOUNT)
FROM SALES
GROUP BY GEOID;

-- 2.
SELECT PID,COUNT(BOXES), SUM(AMOUNT)
FROM SALES
WHERE AMOUNT > 10000
GROUP BY PID;

-- GROUP BY AND JOIN TOGETHER
-- 1.
SELECT G.GEO, COUNT(BOXES) AS 'NO.OF BOXES',SUM(AMOUNT) AS 'TOTAL AMOUNT', AVG(AMOUNT) AS "AVERAGE AMOUNT"
FROM SALES S
JOIN GEO G
ON S.GEOID = G.GEOID
GROUP BY G.GEO;

-- 2.
SELECT PR.CATEGORY, P.TEAM, SUM(S.BOXES), SUM(S.AMOUNT)
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN PRODUCTS PR
ON S.PID = PR.PID
WHERE P.TEAM <> 'Sweeties'
GROUP BY PR.CATEGORY, P.TEAM
ORDER BY PR.CATEGORY, P.TEAM;

-- TOTAL AMOUNT BY TOP 10 PRODUCT
SELECT PR.PRODUCT, SUM(S.AMOUNT) 'TOTAL AMOUNT'
FROM SALES S
JOIN PRODUCTS PR
ON S.PID = PR.PID
GROUP BY PR.PRODUCT
ORDER BY 'TOTAL AMOUNT' DESC
LIMIT 10;

-- RETREIVE TOTAL NO. OF GEOID
SELECT COUNT(GEOID) 
FROM GEO