-- OR operator in SQL
SELECT *
FROM PEOPLE
WHERE TEAM = 'DELISH' OR TEAM = 'JUCIES'
ORDER BY LOCATION;

-- IN operator in SQL
SELECT *
FROM PEOPLE
WHERE TEAM IN('DELISH','JUCIES')
ORDER BY LOCATION;

-- LIKE operator in SQL
-- 'B' AT THE START
-- 1.
SELECT *
FROM PEOPLE
WHERE SALESPERSON LIKE 'B%';

-- 'Y' IN THE LAST
-- 2.
SELECT *
FROM PEOPLE
WHERE SALESPERSON LIKE '%Y';

-- 'B' IN BETWEEN ANYWHERE
-- 3.
SELECT *
FROM PEOPLE
WHERE SALESPERSON LIKE '%B%';

-- 'A' IN THE SECOND POSITION
-- 4.
SELECT *
FROM PEOPLE
WHERE SALESPERSON LIKE '_A%';

-- START WITH 'K' AND END WITH 'Y'
-- 4.
SELECT *
FROM PEOPLE
WHERE SALESPERSON LIKE 'K%Y';