-- MULTIPLE JOINS
-- 1.
SELECT S.SPID, P.TEAM, G.GEO, P.LOCATION, G.REGION
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID;

-- 2.
SELECT S.SPID, P.SALESPERSON, G.GEO, P.LOCATION, S.SALEDATE, PR.PRODUCT, PR.SIZE, S.BOXES, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID
JOIN PRODUCTS PR
ON S.PID = PR.PID;

-- 3.
SELECT S.SPID, P.SALESPERSON, G.GEO, S.SALEDATE, PR.PRODUCT, PR.SIZE, S.BOXES, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID
JOIN PRODUCTS PR
ON S.PID = PR.PID
WHERE BOXES >= 100 AND GEO IN ('USA', 'UK', 'CANADA')
ORDER BY SPID;

-- 4.
SELECT S.SPID, P.SALESPERSON, G.GEO, S.SALEDATE, PR.PRODUCT, PR.SIZE, S.BOXES, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID
JOIN PRODUCTS PR
ON S.PID = PR.PID
LIMIT 5;

-- 5.
SELECT S.SPID, P.SALESPERSON, G.GEO, S.SALEDATE, PR.PRODUCT, PR.SIZE, S.BOXES, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID
JOIN PRODUCTS PR
ON S.PID = PR.PID
WHERE GEO = 'USA'
LIMIT 5;

-- 6.
SELECT S.SPID, P.SALESPERSON, G.GEO, S.SALEDATE, PR.PRODUCT, PR.SIZE, S.BOXES, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
JOIN GEO G
ON S.GEOID = G.GEOID
JOIN PRODUCTS PR
ON S.PID = PR.PID
LIMIT 5 OFFSET 3;