-- USIN CASE TO CREATE BRANCHING LOGIC IN SQL
SELECT SALEDATE, AMOUNT,
       CASE   WHEN AMOUNT < 1000 THEN 'UNDER 1K'
              WHEN AMOUNT < 5000 THEN 'UNDER 5K'
              WHEN AMOUNT < 10000 THEN 'UNDER 10K'
	      ELSE '10K or MORE'
	   END AS 'AMOUNT CATEGORY'
FROM SALES;

# JOINS
-- JOINING THE SALES TABLE AND PEOPLES TABLE TO COLLECT THE PERSONS DATA
-- 1.
SELECT S.SPID, P.SALESPERSON, P.LOCATION ,S.CUSTOMERS, P.TEAM ,S.SALEDATE, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
WHERE YEAR(S.SALEDATE) = 2022 AND AMOUNT >= 10000
ORDER BY AMOUNT DESC;

-- 2.
SELECT DISTINCT(P.SALESPERSON), S.SPID ,P.LOCATION, S.CUSTOMERS, P.TEAM, S.SALEDATE, S.AMOUNT
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
WHERE P.TEAM IN ('','DELISH') AND YEAR(S.SALEDATE) = 2022 AND S.AMOUNT >= 10000 AND S.CUSTOMERS >=100
ORDER BY P.SALESPERSON;

-- 3.
SELECT P.SALESPERSON, S.SPID ,P.LOCATION, S.CUSTOMERS, P.TEAM, S.SALEDATE, S.AMOUNT 
FROM SALES S
JOIN PEOPLE P
ON S.SPID = P.SPID
WHERE P.TEAM NOT IN ('JUCIES','DELISH') AND S.AMOUNT >= 10000 AND S.CUSTOMERS >=100
ORDER BY P.SALESPERSON ASC, AMOUNT DESC;